
# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               오늘도 개발자
tagline:             'Backend Developer'
description:         '언제나 개발하기를 즐기는 개발자 입니다.'
url:                 https://akageun.github.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Geun
  url:               https://akageun.github.com
  email:             akageun@gmail.com

# Custom vars
version:             0.0.1

plugins: [
  jekyll-paginate,
  jekyll-gist
]
# Tag setting
#collections:
#  tags:
#    output: true
#    permalink: /tags/:path/
#defaults:
#  - scope:
#      path: ''
#      type: tags
#    values:
#      layout: tag
google_analytics:
  ua: 'UA-141840466-1'
github:
  repo: 'https://github.com/akageun'

category_dir: category/
tag_dir: tag/

paginate_path: "/page/:num/"