title: Dev Blog
description: Development Blog
author: akageun
github: https://github.com/akageun
#about: I'm Programmer for Python & Django. I've made quite a few web apps, especially on Django.
#disqus_shortname: stackproblems
google_analytics: UA-141840466-1
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      link: "https://github.com/akageun"
urls:
    - text: About Me
      url: /about/
    # - text: My Projects
    #   url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://akageun.github.io"
baseurl: ""
paginate: 20 #페이지 당 보여질 글 수
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']


